version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file: .development.env
    container_name: postgres-db
    volumes:
      - ./pgdata1:/var/lib/postgresql/data
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tusharchy/nest-and-postgres-application:latest
    env_file: .development.env
    ports:
      - "3000:3000"
    container_name: nest-todo-app-be
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  pgdata:
  pgadmin-data: